### ISSUE TITLE
Reconcile "live view" web server with "Standby mode" web server

### ISSUE THREAD

**Issue by jancurn** [apifytech/actor-specs#40]
Currently, the Actor can implement two separate web servers, running on different ports, and accessible on two different URLs. But that is very confusing and overly complicated. 

IMO we should have just one Actor web server, potentially with OpenAPI schema for its API, and have it accessible at container-specific live view URL (`ACTOR_WEB_SERVER_URL`) as well as external non-Actor-specific Standby URL (`ACTOR_EXTERNAL_STANDBY_URL`). After all, the feature is called "Standby mode", not a "Standby web server", which would indicate a presence of a specialised web server.

If we do this, the only thing we'd lose is ability to run two user-oriented websites on URLs such as:

- `https://5nysmbrn7yn.runs.apify.net`
- `https://bob--screenshot-taker.apify.actor`

As those would be both handled by the single web server. But in what kind of situation would we need these two to be separate web servers, especially when the live-view one lives on randomly generated URL? I can't think of any... Plus a workaround exists, you can just instruct users to use this live-view URL instead:

- `https://5nysmbrn7yn.runs.apify.net/another-view`

Altogether, having two web servers makes everything more complicated without any clear benefit, so it's not worth it.

**Comment by fnesveda** [comment]
What this means:

- Actors will run one web server handling requests from both conductor and Standby
- Environment variables passed to Actors will be:
  - `ACTOR_WEB_SERVER_URL` - stays the same
  - `ACTOR_WEB_SERVER_PORT` - stays the same
  - `ACTOR_EXTERNAL_STANDBY_URL` - new, will contain e.g. `https://bob--screenshot-taker.apify.actor/` 
    - should it be `ACTOR_EXTERNAL_STANDBY_URL`
    - or `ACTOR_STANDBY_EXTERNAL_URL`?
  - `ACTOR_STANDBY_PORT` - changes, will contain same value as `ACTOR_WEB_SERVER_PORT` by default
- We will stop mentioning `ACTOR_STANDBY_PORT` in the docs, we'll direct people to start using `ACTOR_WEB_SERVER_PORT` instead. We'll have to update Actor templates, SDK, blog post etc. as well
- `ACTOR_STANDBY_PORT` will continue working indefinitely to keep backwards compatibility
- When receiving a request from conductor, Standby idle timeout will not be increased

@jancurn does it make sense like this, or did you think about it some other way?

**Comment by jancurn** [comment]
@fnesveda thanks for looking into it, it's exactly as you write.  

Regarding the naming, how about simply `ACTOR_STANDBY_URL` ? The "external" doesn't add any information, the web server URL is also "external". 

So if you guys are happy with this, I'll update this document, drop `ACTOR_STANDBY_PORT` and rename to `ACTOR_STANDBY_URL`.

**Comment by jancurn** [comment]
FYI, I updated the whitepaper to reflect the above.

**Comment by jancurn** [comment]
@fnesveda please guys can you keep us posted about the status of this?

**Comment by fnesveda** [comment]
Sure
